[package]
name = "spagreppi"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
# globally search a regular expression and print
# add CASE_INSENSITIVE to make the research insensitive
[dependencies]
